name: Linux
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Add python3 to PATH
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install conan
        run: pip3 install conan
      - name: Get CMake
        uses: symbitic/install-cmake@master
      - name: Install clang
        run: tools/build_scripts/ubuntu_18_04_x86_64_install_clang.sh
      - name: Build and test (Debug)
        run: tools/build_scripts/linux_debug_build.sh
