name: x86_64 Linux
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add python3 to PATH
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install conan
        run: pip3 install conan
      - name: Get CMake
        uses: symbitic/install-cmake@master